# Generated by Django 4.1.1 on 2023-09-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appContrato', '0001_initial'),
        ('appArbitro', '0002_initial'),
        ('appCompeticion', '0001_initial'),
        ('appEquipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('ciudad_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('norma', models.CharField(max_length=5)),
                ('pais_id', models.ForeignKey(db_column='pais_id', on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.pais')),
            ],
            options={
                'verbose_name_plural': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='encuentro',
            fields=[
                ('encuentro_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('resultado_local', models.CharField(choices=[('G', 'GANADO'), ('E', 'EMPATADO'), ('P', 'PERDIDO')], max_length=1)),
                ('resultado_visita', models.CharField(choices=[('G', 'GANADO'), ('E', 'EMPATADO'), ('P', 'PERDIDO')], max_length=1)),
                ('resultado_goles_local', models.IntegerField()),
                ('resultado_goles_visita', models.IntegerField()),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('humedad', models.CharField(max_length=4)),
                ('clima', models.CharField(max_length=4)),
                ('estado_jugado', models.BooleanField()),
                ('alineacion_local', models.ForeignKey(blank=True, db_column='alineacion_local', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alineacion_local', to='appEquipo.alineacion')),
                ('alineacion_visita', models.ForeignKey(blank=True, db_column='alineacion_visita', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alineacion_visita', to='appEquipo.alineacion')),
                ('competicion_id', models.ForeignKey(db_column='competicion_id', on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.competicion')),
                ('equipo_local', models.ForeignKey(db_column='equipo_local', on_delete=django.db.models.deletion.CASCADE, related_name='equipo_local', to='appEquipo.equipo')),
                ('equipo_visita', models.ForeignKey(db_column='equipo_visita', on_delete=django.db.models.deletion.CASCADE, related_name='equipo_visita', to='appEquipo.equipo')),
                ('fase', models.ForeignKey(db_column='fase', on_delete=django.db.models.deletion.CASCADE, related_name='fase', to='appCompeticion.fase')),
            ],
            options={
                'verbose_name_plural': 'encuentro',
            },
        ),
        migrations.CreateModel(
            name='estado',
            fields=[
                ('estado_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'estado',
            },
        ),
        migrations.CreateModel(
            name='evento',
            fields=[
                ('evento_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=30)),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'evento',
            },
        ),
        migrations.CreateModel(
            name='formacion',
            fields=[
                ('formacion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'formacion',
            },
        ),
        migrations.CreateModel(
            name='sede',
            fields=[
                ('sede_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('alias', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('fecha_inauguracion', models.DateField()),
                ('estado', models.CharField(choices=[('SD', 'SUSPENDIDO DEFINITIVAMENTE'), ('DI', 'DISPONIBLE'), ('EM', 'EN MANTENIMIENTO'), ('ND', 'NO DISPONIBLE'), ('ST', 'SUSPENDIDO TEMPORALMENTE')], default='DI', max_length=2)),
                ('ciudad_id', models.ForeignKey(db_column='ciudad_id', on_delete=django.db.models.deletion.CASCADE, to='appPartido.ciudad')),
            ],
            options={
                'verbose_name_plural': 'sede',
            },
        ),
        migrations.CreateModel(
            name='evento_persona',
            fields=[
                ('encuentro_evento_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('suceso', models.CharField(default='ABC', max_length=5)),
                ('tipo_suceso', models.CharField(blank=True, choices=[('E', 'ENTRADA'), ('S', 'SALIDA')], max_length=1, null=True)),
                ('tiempo', models.IntegerField()),
                ('observacion', models.CharField(blank=True, max_length=50, null=True)),
                ('encuentro_id', models.ForeignKey(db_column='encuentro_id', on_delete=django.db.models.deletion.CASCADE, to='appPartido.encuentro')),
                ('evento_id', models.ForeignKey(db_column='evento_id', on_delete=django.db.models.deletion.CASCADE, to='appPartido.evento')),
                ('persona_id', models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, to='appContrato.persona')),
            ],
            options={
                'verbose_name_plural': 'evento_persona',
            },
        ),
        migrations.AddField(
            model_name='encuentro',
            name='formacion_local',
            field=models.ForeignKey(blank=True, db_column='formacion_local', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formacion_local', to='appPartido.formacion'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='formacion_visita',
            field=models.ForeignKey(blank=True, db_column='formacion_visita', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formacion_visita', to='appPartido.formacion'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='grupo',
            field=models.ForeignKey(db_column='grupo', on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='appCompeticion.grupo'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='sede_id',
            field=models.ForeignKey(blank=True, db_column='sede_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appPartido.sede'),
        ),
        migrations.AddField(
            model_name='encuentro',
            name='terna_arbitral_id',
            field=models.ForeignKey(db_column='terna_arbitral_id', on_delete=django.db.models.deletion.CASCADE, to='appArbitro.terna_arbitral'),
        ),
    ]
