# Generated by Django 4.1.1 on 2023-11-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='estado_jugado',
            field=models.CharField(choices=[('J', 'JUGADO'), ('N', 'NO JUGADO'), ('E', 'EN JUEGO'), ('S', 'SUSPENDIDO')], default='DI', max_length=2),
        ),
    ]
