# Generated by Django 4.1.1 on 2023-10-23 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuentro',
            name='alineacion_local',
        ),
        migrations.RemoveField(
            model_name='encuentro',
            name='alineacion_visita',
        ),
        migrations.RemoveField(
            model_name='encuentro',
            name='formacion_local',
        ),
        migrations.RemoveField(
            model_name='encuentro',
            name='formacion_visita',
        ),
        migrations.RemoveField(
            model_name='encuentro',
            name='humedad',
        ),
        migrations.RemoveField(
            model_name='encuentro',
            name='resultado_goles_local',
        ),
        migrations.RemoveField(
            model_name='encuentro',
            name='resultado_goles_visita',
        ),
        migrations.RemoveField(
            model_name='encuentro',
            name='resultado_local',
        ),
        migrations.RemoveField(
            model_name='encuentro',
            name='resultado_visita',
        ),
        migrations.RemoveField(
            model_name='encuentro',
            name='terna_arbitral_id',
        ),
    ]
