# Generated by Django 4.1.1 on 2023-10-24 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0002_initial'),
        ('appPartido', '0002_remove_encuentro_alineacion_local_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='descripcion_encuentro',
            fields=[
                ('descripcion_encuentro_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('goles', models.CharField(max_length=4)),
                ('goles_ronda_penales', models.CharField(max_length=4)),
                ('resultado', models.CharField(choices=[('G', 'GANADO'), ('E', 'EMPATADO'), ('P', 'PERDIDO')], max_length=1)),
                ('encuentro', models.ForeignKey(blank=True, db_column='encuentro_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descripcion_encuentros', to='appPartido.encuentro')),
                ('equipo', models.ForeignKey(blank=True, db_column='equipo_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descripcion_encuentros', to='appEquipo.equipo')),
                ('formacion', models.ForeignKey(blank=True, db_column='formacion_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descripcion_encuentros', to='appPartido.formacion')),
            ],
            options={
                'verbose_name_plural': 'descripcion_encuentro',
            },
        ),
    ]
