# Generated by Django 4.1.1 on 2023-10-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0003_descripcion_encuentro'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcion_encuentro',
            name='tipo_equipo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
