# Generated by Django 4.1.1 on 2023-11-02 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0004_descripcion_encuentro_tipo_equipo'),
    ]

    operations = [
       
        # migrations.RemoveField(
        #     model_name='evento_persona',
        #     name='evento_id',
        # ),
        # migrations.AddField(
        #     model_name='sede',
        #     name='imagen',
        #     field=models.ImageField(blank=True, default='sede/imagen_default.png', null=True, upload_to='sede/'),
        # ),
        # migrations.AlterField(
        #     model_name='sede',
        #     name='alias',
        #     field=models.CharField(max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='sede',
        #     name='nombre',
        #     field=models.CharField(max_length=255),
        # ),
        # migrations.DeleteModel(
        #     name='evento',
        # ),
        # migrations.AddField(
        #     model_name='evento_persona',
        #     name='tipo_evento_id',
        #     field=models.ForeignKey(db_column='tipo_evento_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appPartido.tipo_evento'),
        # ),
    ]
