# Generated by Django 4.1.1 on 2023-11-02 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0004_remove_alineacion_equipo_alineacion_id_and_more'),
        ('appPartido', '0005_tipo_evento_remove_evento_persona_evento_id_and_more'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='tipo_evento',
        #     fields=[
        #         ('tipo_evento_id', models.BigAutoField(primary_key=True, serialize=False)),
        #         ('nombre', models.CharField(max_length=30)),
        #         ('descripcion', models.CharField(max_length=300)),
        #         ('estado', models.BooleanField()),
        #         ('logo_tipo_evento', models.ImageField(blank=True, default='jugador/logo_default.png', null=True, upload_to='jugador/')),
        #     ],
        #     options={
        #         'verbose_name_plural': 'tipo_evento',
        #     },
        # ),
        # migrations.RemoveField(
        #     model_name='evento',
        #     name='descripcion',
        # ),
        # migrations.RemoveField(
        #     model_name='evento',
        #     name='estado',
        # ),
        # migrations.AddField(
        #     model_name='evento',
        #     name='alineacion1_id',
        #     field=models.ForeignKey(db_column='alineacion_id1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_alineacion1', to='appEquipo.alineacionequipo'),
        # ),
        # migrations.AddField(
        #     model_name='evento',
        #     name='alineacion2_id',
        #     field=models.ForeignKey(db_column='alineacion_id2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_alineacion2', to='appEquipo.alineacionequipo'),
        # ),
        # migrations.AddField(
        #     model_name='evento',
        #     name='cantidad',
        #     field=models.IntegerField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='evento',
        #     name='encuentro_id',
        #     field=models.ForeignKey(db_column='encuentro_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appPartido.encuentro'),
        # ),
        # migrations.AddField(
        #     model_name='evento',
        #     name='motivo',
        #     field=models.CharField(blank=True, max_length=50, null=True),
        # ),
        # migrations.AddField(
        #     model_name='evento',
        #     name='tiempo_extra',
        #     field=models.TimeField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='evento',
        #     name='tiempo_reglamentario',
        #     field=models.TimeField(null=True),
        # ),
        # migrations.AddField(
        #     model_name='sede',
        #     name='imagen',
        #     field=models.ImageField(blank=True, default='sede/imagen_default.png', null=True, upload_to='sede/'),
        # ),
        # migrations.AlterField(
        #     model_name='sede',
        #     name='alias',
        #     field=models.CharField(max_length=100),
        # ),
        # migrations.AlterField(
        #     model_name='sede',
        #     name='nombre',
        #     field=models.CharField(max_length=255),
        # ),
        # migrations.DeleteModel(
        #     name='evento_persona',
        # ),
        # migrations.AddField(
        #     model_name='evento',
        #     name='tipo_evento_id',
        #     field=models.ForeignKey(db_column='tipo_evento_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appPartido.tipo_evento'),
        # ),
    ]
