# Generated by Django 4.1.1 on 2023-11-02 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0005_remove_alineacion_equipo_alineacion_id_and_more'),
        ('appPartido', '0006_tipo_evento_remove_evento_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventoPersona',
            fields=[
                ('evento_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tiempo_reglamentario', models.TimeField(null=True)),
                ('tiempo_extra', models.TimeField(null=True)),
                ('motivo', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('alineacion1_id', models.ForeignKey(db_column='alineacion_id1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_alineacion1', to='appEquipo.alineacionequipo')),
                ('alineacion2_id', models.ForeignKey(db_column='alineacion_id2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos_alineacion2', to='appEquipo.alineacionequipo')),
                ('encuentro_id', models.ForeignKey(db_column='encuentro_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appPartido.encuentro')),
            ],
            options={
                'verbose_name_plural': 'evento',
            },
        ),
    ]
