# Generated by Django 4.1.1 on 2023-11-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0013_alter_encuentro_estado_jugado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='estado_jugado',
            field=models.CharField(choices=[('J', 'JUGADO'), ('N', 'NO JUGADO'), ('E', 'EN JUEGO'), ('S', 'SUSPENDIDO')], db_column='estado_jugado', default='N', max_length=1, null=True),
        ),
    ]
