# Generated by Django 4.1.1 on 2023-11-13 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0015_alter_detalle_grupo_grupo_id'),
        ('appPartido', '0015_alter_evento_alineacion1_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='grupo',
            field=models.ForeignKey(blank=True, db_column='grupo', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupo', to='appCompeticion.grupo'),
        ),
    ]
