# Generated by Django 4.1.1 on 2023-11-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPartido', '0016_alter_descripcion_encuentro_goles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion_encuentro',
            name='goles_ronda_penales',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
