# Generated by Django 4.1.1 on 2023-11-02 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEquipo', '0004_remove_alineacion_equipo_alineacion_id_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='alineacion_equipo',
        #     name='alineacion_id',
        # ),
        # migrations.RemoveField(
        #     model_name='alineacion_equipo',
        #     name='contrato_id',
        # ),
        # migrations.RemoveField(
        #     model_name='alineacion_equipo',
        #     name='equipo_id',
        # ),
        # migrations.RemoveField(
        #     model_name='alineacion_equipo',
        #     name='posicion_jugador_id',
        # ),
        # migrations.DeleteModel(
        #     name='alineacion',
        # ),
        # migrations.DeleteModel(
        #     name='alineacion_equipo',
        # ),
    ]
