# Generated by Django 4.1.1 on 2023-09-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='competicion',
            fields=[
                ('competicion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logo_competicion', models.ImageField(blank=True, default='competicion/logo/logo_default.png', null=True, upload_to='competicion/logo/')),
                ('nombre', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
                ('fecha_inicio', models.DateField(blank=True, default='1990-12-12', null=True)),
                ('fecha_fin', models.DateField(blank=True, default='1990-12-12', null=True)),
            ],
            options={
                'verbose_name_plural': 'competicion',
            },
        ),
        migrations.CreateModel(
            name='deporte',
            fields=[
                ('deporte_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'deporte',
            },
        ),
        migrations.CreateModel(
            name='detalle_grupo',
            fields=[
                ('detalle_grupo_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'detalle_grupo',
            },
        ),
        migrations.CreateModel(
            name='fase',
            fields=[
                ('fase_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'fase',
            },
        ),
        migrations.CreateModel(
            name='grupo',
            fields=[
                ('grupo_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('pais_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('logo_bandera', models.ImageField(blank=True, default='bandera/bandera_default.png', null=True, upload_to='bandera/')),
                ('nombre', models.CharField(max_length=30)),
                ('sigla', models.CharField(default='', max_length=3)),
            ],
            options={
                'verbose_name_plural': 'pais',
            },
        ),
        migrations.CreateModel(
            name='tipo_competicion',
            fields=[
                ('tipo_competicion_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'tipo_competicion',
            },
        ),
        migrations.CreateModel(
            name='tabla',
            fields=[
                ('tabla_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ganado', models.IntegerField()),
                ('perdido', models.IntegerField()),
                ('empatado', models.IntegerField()),
                ('goles_favor', models.IntegerField()),
                ('goles_contra', models.IntegerField()),
                ('tarjetas_amarillas', models.IntegerField()),
                ('tarjetas_rojas', models.IntegerField()),
                ('puntos', models.IntegerField()),
                ('competicion_id', models.ForeignKey(db_column='competicion_id', on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.competicion')),
            ],
            options={
                'verbose_name_plural': 'tabla',
            },
        ),
    ]
