# Generated by Django 4.1.1 on 2023-11-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0006_remove_competicion_tipo_competicion_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competicion',
            name='organizacion_id',
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='nombre_oficial',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='siglas',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='organizacion',
            name='tipo',
            field=models.CharField(choices=[('F', 'FEDERACIÓN NACIONAL'), ('I', 'FEDERACIÓN INTERNACIONAL'), ('C', 'CONFEDERACIÓN'), ('L', 'LIGA'), ('A', 'ASOCIACIÓN')], default='I', max_length=1),
        ),
    ]
