# Generated by Django 4.1.1 on 2023-11-12 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0012_alter_detalle_grupo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacion',
            name='tipo',
            field=models.CharField(choices=[('F', 'FEDERACIÓN NACIONAL'), ('I', 'FEDERACIÓN INTERNACIONAL'), ('C', 'CONFEDERACIÓN'), ('L', 'LIGA'), ('A', 'ASOCIACIÓN')], default='I', max_length=1),
        ),
    ]
