# Generated by Django 4.1.1 on 2023-11-13 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appCompeticion', '0014_alter_detalle_grupo_grupo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_grupo',
            name='grupo_id',
            field=models.ForeignKey(blank=True, db_column='grupo_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='appCompeticion.grupo'),
        ),
    ]
